version: 1.1.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
  publish_nuget: true
test:
  assemblies:
    only:
      - '**\bin\**\*.UnitTests.dll'
deploy:
  provider: NuGet
  api_key:
    secure: EqocuRN+dPLo43f6XC9SZIry4fYwoAibK7wTAte9Rrbc4Xl/OyWhGo75yv3/Rs+/
  skip_symbols: false
  artifact: /.*\.nupkg/
notifications:
  - provider: Email
    to:
      - anders@busted-janum.dk
    subject: 'Build {{projectName}} {{buildVersion}} {{status}}'         
    message: "{{message}}, {{commitId}}"
    on_build_status_changed: true
