version: 1.1.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
before_build:
  - cmd: nuget restore
configuration: 
  Release
build:
  verbosity: minimal
#  publish_nuget: true
test:
  assemblies:
    only:
      - '**\bin\**\*.UnitTests.dll'
after_build:
  - ps: nuget pack Grumpy.Common\bin\Release\Grumpy.Common.nuspec -Version $env:APPVEYOR_BUILD_VERSION
deploy:
  provider: NuGet
  api_key:
    secure: EqocuRN+dPLo43f6XC9SZIry4fYwoAibK7wTAte9Rrbc4Xl/OyWhGo75yv3/Rs+/
  skip_symbols: false
  artifact: /.*\.nupkg/

